/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthGalleryRouteImport } from './routes/_auth.gallery'
import { Route as AuthSavedMessagesRouteImport } from './routes/_auth.saved-messages'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ShareChatIdRouteImport } from './routes/share.$chatId'
import { Route as AuthChatChatIdRouteImport } from './routes/_auth.chat.$chatId'
import { Route as AuthSavedMessagesIndexRouteImport } from './routes/_auth.saved-messages.index'
import { Route as AuthSavedMessagesChatIdRouteImport } from './routes/_auth.saved-messages.$chatId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGalleryRoute = AuthGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSavedMessagesRoute = AuthSavedMessagesRouteImport.update({
  id: '/saved-messages',
  path: '/saved-messages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareChatIdRoute = ShareChatIdRouteImport.update({
  id: '/share/$chatId',
  path: '/share/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChatChatIdRoute = AuthChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSavedMessagesIndexRoute = AuthSavedMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSavedMessagesRoute,
} as any)
const AuthSavedMessagesChatIdRoute = AuthSavedMessagesChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthSavedMessagesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/gallery': typeof AuthGalleryRoute
  '/saved-messages': typeof AuthSavedMessagesRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/share/$chatId': typeof ShareChatIdRoute
  '/chat/$chatId': typeof AuthChatChatIdRoute
  '/saved-messages/$chatId': typeof AuthSavedMessagesChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/saved-messages/': typeof AuthSavedMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/gallery': typeof AuthGalleryRoute
  '/settings': typeof AuthSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/share/$chatId': typeof ShareChatIdRoute
  '/': typeof AuthIndexRoute
  '/chat/$chatId': typeof AuthChatChatIdRoute
  '/saved-messages/$chatId': typeof AuthSavedMessagesChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/saved-messages': typeof AuthSavedMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/gallery': typeof AuthGalleryRoute
  '/_auth/saved-messages': typeof AuthSavedMessagesRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/share/$chatId': typeof ShareChatIdRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/chat/$chatId': typeof AuthChatChatIdRoute
  '/_auth/saved-messages/$chatId': typeof AuthSavedMessagesChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/saved-messages/': typeof AuthSavedMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/gallery'
    | '/saved-messages'
    | '/settings'
    | '/api/chat'
    | '/share/$chatId'
    | '/chat/$chatId'
    | '/saved-messages/$chatId'
    | '/api/auth/$'
    | '/saved-messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/gallery'
    | '/settings'
    | '/api/chat'
    | '/share/$chatId'
    | '/'
    | '/chat/$chatId'
    | '/saved-messages/$chatId'
    | '/api/auth/$'
    | '/saved-messages'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/gallery'
    | '/_auth/saved-messages'
    | '/_auth/settings'
    | '/api/chat'
    | '/share/$chatId'
    | '/_auth/'
    | '/_auth/chat/$chatId'
    | '/_auth/saved-messages/$chatId'
    | '/api/auth/$'
    | '/_auth/saved-messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ShareChatIdRoute: typeof ShareChatIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gallery': {
      id: '/_auth/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthGalleryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/saved-messages': {
      id: '/_auth/saved-messages'
      path: '/saved-messages'
      fullPath: '/saved-messages'
      preLoaderRoute: typeof AuthSavedMessagesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$chatId': {
      id: '/share/$chatId'
      path: '/share/$chatId'
      fullPath: '/share/$chatId'
      preLoaderRoute: typeof ShareChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/chat/$chatId': {
      id: '/_auth/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthChatChatIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/saved-messages/': {
      id: '/_auth/saved-messages/'
      path: '/'
      fullPath: '/saved-messages/'
      preLoaderRoute: typeof AuthSavedMessagesIndexRouteImport
      parentRoute: typeof AuthSavedMessagesRoute
    }
    '/_auth/saved-messages/$chatId': {
      id: '/_auth/saved-messages/$chatId'
      path: '/$chatId'
      fullPath: '/saved-messages/$chatId'
      preLoaderRoute: typeof AuthSavedMessagesChatIdRouteImport
      parentRoute: typeof AuthSavedMessagesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthSavedMessagesRouteChildren {
  AuthSavedMessagesChatIdRoute: typeof AuthSavedMessagesChatIdRoute
  AuthSavedMessagesIndexRoute: typeof AuthSavedMessagesIndexRoute
}

const AuthSavedMessagesRouteChildren: AuthSavedMessagesRouteChildren = {
  AuthSavedMessagesChatIdRoute: AuthSavedMessagesChatIdRoute,
  AuthSavedMessagesIndexRoute: AuthSavedMessagesIndexRoute,
}

const AuthSavedMessagesRouteWithChildren =
  AuthSavedMessagesRoute._addFileChildren(AuthSavedMessagesRouteChildren)

interface AuthRouteChildren {
  AuthGalleryRoute: typeof AuthGalleryRoute
  AuthSavedMessagesRoute: typeof AuthSavedMessagesRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthChatChatIdRoute: typeof AuthChatChatIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGalleryRoute: AuthGalleryRoute,
  AuthSavedMessagesRoute: AuthSavedMessagesRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthChatChatIdRoute: AuthChatChatIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ShareChatIdRoute: ShareChatIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
